all_columns = {"發生年度": "accident_year",
               "發生月份": "accident_month",
               "發生日期": "accident_date",
               "發生時間": "accident_time",
               "事故類別名稱": "accident_category",
               "處理單位名稱警局層": "police_department",
               "發生地點": "accident_location",
               "天候名稱": "weather_condition",
               "光線名稱": "light_condition",
               "道路類別-第1當事者-名稱": "road_type_primary_party",
               "速限-第1當事者": "speed_limit_primary_party",
               "道路型態大類別名稱": "road_form_major",
               "道路型態子類別名稱": "road_form_minor",
               "事故位置大類別名稱": "accident_position_major",
               "事故位置子類別名稱": "accident_position_minor",
               "路面狀況-路面鋪裝名稱": "road_surface_pavement",
               "路面狀況-路面狀態名稱": "road_surface_condition",
               "路面狀況-路面缺陷名稱": "road_surface_defect",
               "道路障礙-障礙物名稱": "road_obstacle",
               "道路障礙-視距品質名稱": "sight_distance_quality",
               "道路障礙-視距名稱": "sight_distance",
               "號誌-號誌種類名稱": "traffic_signal_type",
               "號誌-號誌動作名稱": "traffic_signal_action",
               "車道劃分設施-分向設施大類別名稱": "lane_divider_direction_major",
               "車道劃分設施-分向設施子類別名稱": "lane_divider_direction_minor",
               "車道劃分設施-分道設施-快車道或一般車道間名稱": "lane_divider_main_general",
               "車道劃分設施-分道設施-快慢車道間名稱": "lane_divider_fast_slow",
               "車道劃分設施-分道設施-路面邊線名稱": "lane_edge_marking",
               "事故類型及型態大類別名稱": "accident_type_major",
               "事故類型及型態子類別名稱": "accident_type_minor",
               "肇因研判大類別名稱-主要": "cause_analysis_major_primary",
               "肇因研判子類別名稱-主要": "cause_analysis_minor_primary",
               "死亡受傷人數": "casualties_count",
               "當事者順位": "party_sequence",
               "當事者區分-類別-大類別名稱-車種": "vehicle_type_major",
               "當事者區分-類別-子類別名稱-車種": "vehicle_type_minor",
               "當事者屬-性-別名稱": "gender",
               "當事者事故發生時年齡": "age",
               "保護裝備名稱": "protective_equipment",
               "行動電話或電腦或其他相類功能裝置名稱": "mobile_device_usage",
               "當事者行動狀態大類別名稱": "party_action_major",
               "當事者行動狀態子類別名稱": "party_action_minor",
               "車輛撞擊部位大類別名稱-最初": "impact_point_major_initial",
               "車輛撞擊部位子類別名稱-最初": "impact_point_minor_initial",
               "車輛撞擊部位大類別名稱-其他": "impact_point_major_other",
               "車輛撞擊部位子類別名稱-其他": "impact_point_minor_other",
               "肇因研判大類別名稱-個別": "cause_analysis_major_individual",
               "肇因研判子類別名稱-個別": "cause_analysis_minor_individual",
               "肇事逃逸類別名稱-是否肇逃": "hit_and_run",
               "經度": "longitude",
               "緯度": "latitude",
               "共享經濟或外送平台的名稱": "serving_sharing_economy_or_delivery",
               }

dim_accident_type_col_map = {"事故類別名稱": "accident_category",
                             "事故位置大類別名稱": "accident_position_major",
                             "事故位置子類別名稱": "accident_position_minor",
                             "事故類型及型態大類別名稱": "accident_type_major",
                             "事故類型及型態子類別名稱": "accident_type_minor", }

dim_lane_design_col_map = {"車道劃分設施-分向設施大類別名稱": "lane_divider_direction_major",
                           "車道劃分設施-分向設施子類別名稱": "lane_divider_direction_minor",
                           "車道劃分設施-分道設施-快車道或一般車道間名稱": "lane_divider_main_general",
                           "車道劃分設施-分道設施-快慢車道間名稱": "lane_divider_fast_slow",
                           "車道劃分設施-分道設施-路面邊線名稱": "lane_edge_marking",
                           }

dim_road_design_col_map = {"道路類別-第1當事者-名稱": "road_type_primary_party",
                           "道路型態大類別名稱": "road_form_major",
                           "道路型態子類別名稱": "road_form_minor",
                           }

fact_accident_main_col_origin_map = {"事故類別名稱": "accident_category",
                                     "事故位置大類別名稱": "accident_position_major",
                                     "事故位置子類別名稱": "accident_position_minor",
                                     "事故類型及型態大類別名稱": "accident_type_major",
                                     "事故類型及型態子類別名稱": "accident_type_minor",
                                     "發生日期": "accident_date",
                                     "發生時間": "accident_time",
                                     "死亡受傷人數": "casualties_count",
                                     "經度": "longitude",
                                     "緯度": "latitude",
                                     }

fact_accident_env_col_origin_map = {"發生日期": "accident_date",
                                    "發生時間": "accident_time",
                                    "天候名稱": "weather_condition",
                                    "光線名稱": "light_condition",
                                    "道路類別-第1當事者-名稱": "road_type_primary_party",
                                    "速限-第1當事者": "speed_limit_primary_party",
                                    "道路型態大類別名稱": "road_form_major",
                                    "道路型態子類別名稱": "road_form_minor",
                                    "路面狀況-路面鋪裝名稱": "road_surface_pavement",
                                    "路面狀況-路面狀態名稱": "road_surface_condition",
                                    "路面狀況-路面缺陷名稱": "road_surface_defect",
                                    "道路障礙-障礙物名稱": "road_obstacle",
                                    "道路障礙-視距品質名稱": "sight_distance_quality",
                                    "道路障礙-視距名稱": "sight_distance",
                                    "號誌-號誌種類名稱": "traffic_signal_type",
                                    "號誌-號誌動作名稱": "traffic_signal_action",
                                    "車道劃分設施-分向設施大類別名稱": "lane_divider_direction_major",
                                    "車道劃分設施-分向設施子類別名稱": "lane_divider_direction_minor",
                                    "車道劃分設施-分道設施-快車道或一般車道間名稱": "lane_divider_main_general",
                                    "車道劃分設施-分道設施-快慢車道間名稱": "lane_divider_fast_slow",
                                    "車道劃分設施-分道設施-路面邊線名稱": "lane_edge_marking",
                                    "經度": "longitude",
                                    "緯度": "latitude",
                                    }

fact_accident_human_col_origin_map = {"發生日期": "accident_date",
                                      "發生時間": "accident_time",
                                      "經度": "longitude",
                                      "緯度": "latitude",
                                      "當事者順位": "party_sequence",
                                      "當事者屬-性-別名稱": "gender",
                                      "當事者事故發生時年齡": "age",
                                      "保護裝備名稱": "protective_equipment",
                                      "行動電話或電腦或其他相類功能裝置名稱": "mobile_device_usage",
                                      "當事者行動狀態大類別名稱": "party_action_major",
                                      "當事者行動狀態子類別名稱": "party_action_minor",
                                      "當事者區分-類別-大類別名稱-車種": "vehicle_type_major",
                                      "當事者區分-類別-子類別名稱-車種": "vehicle_type_minor",
                                      "肇因研判大類別名稱-個別": "cause_analysis_major_individual",
                                      "肇因研判子類別名稱-個別": "cause_analysis_minor_individual",
                                      "共享經濟或外送平台的名稱": "serving_sharing_economy_or_delivery",
                                      "車輛撞擊部位大類別名稱-最初": "impact_point_major_initial",
                                      "車輛撞擊部位子類別名稱-最初": "impact_point_minor_initial",
                                      "車輛撞擊部位大類別名稱-其他": "impact_point_major_other",
                                      "車輛撞擊部位子類別名稱-其他": "impact_point_minor_other",
                                      "肇事逃逸類別名稱-是否肇逃": "hit_and_run",
                                      }
